  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kafka-cluster-config
    namespace: kafka
  data:
    metrics-config: |
      lowercaseOutputName: true
      rules :
        - pattern: "kafka.server<type=ReplicaManager, name=UnderReplicatedPartitions><>Value"
          name: "kafka_under_replicated_partitions"
          type: GAUGE
        - pattern: "kafka.server<type=ReplicaManager, name=OfflinePartitionsCount><>Value"
          name: "kafka_offline_partitions_count"
          type: GAUGE
        - pattern: "kafka.server<type=ReplicaManager, name=IsrShrinksPerSec><>Value"
          name: "kafka_isr_shrinks_per_sec"
          type: GAUGE
        - pattern: "kafka.server<type=ReplicaManager, name=IsrExpandsPerSec><>Value"
          name: "kafka_isr_expands_per_sec"
          type: GAUGE
        - pattern: "kafka.server<type=BrokerTopicMetrics, name=MessagesInPerSec, topic=(.+)><>Value"
          name: "kafka_messages_in_per_sec"
          labels:
            topic: "$1"
          type: GAUGE
      
        - pattern: "kafka.network<type=RequestMetrics, name=TotalTimeMs, request=(.+)><>Value"
          name: "kafka_request_total_time_ms"
          labels:
            request: "$1"
          type: GAUGE
        - pattern: "kafka.network<type=RequestMetrics, name=RequestsPerSec, request=(.+)><>Value"
          name: "kafka_requests_per_sec"
          labels:
            request: "$1"
          type: GAUGE
        - pattern: "kafka.network<type=BrokerTopicMetrics, name=BytesInPerSec><>Value"
          name: "kafka_bytes_in_per_sec"
          type: GAUGE
        - pattern: "kafka.network<type=BrokerTopicMetrics, name=BytesOutPerSec><>Value"
          name: "kafka_bytes_out_per_sec"
          type: GAUGE
      
        - pattern: "kafka.controller<type=KafkaController, name=ActiveControllerCount><>Value"
          name: "kafka_active_controller_count"
          type: GAUGE
        - pattern: "kafka.controller<type=KafkaController, name=OfflinePartitionsCount><>Value"
          name: "kafka_controller_offline_partitions_count"
          type: GAUGE
        - pattern: "kafka.controller<type=ControllerStats, name=LeaderElectionRateAndTimeMs><>Value"
          name: "kafka_leader_election_time_ms"
          type: GAUGE
      
        - pattern: "java.lang<type=Memory><>HeapMemoryUsage.used"
          name: "jvm_heap_memory_used_bytes"
          type: GAUGE
        - pattern: "java.lang<type=Memory><>HeapMemoryUsage.max"
          name: "jvm_heap_memory_max_bytes"
          type: GAUGE
        - pattern: "java.lang<type=Memory><>NonHeapMemoryUsage.used"
          name: "jvm_nonheap_memory_used_bytes"
          type: GAUGE
        - pattern: "java.lang<type=Threading><>ThreadCount"
          name: "jvm_thread_count"
          type: GAUGE
        - pattern: "java.lang<type=GarbageCollector, name=(.+)><>CollectionTime"
          name: "jvm_gc_collection_time_ms"
          labels:
            gc: "$1"
          type: COUNTER
        - pattern: "java.lang<type=GarbageCollector, name=(.+)><>CollectionCount"
          name: "jvm_gc_collection_count"
          labels:
            gc: "$1"
          type: COUNTER