apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    authorization:
      type: simple
    listeners:
      - name: tls-sasl
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
    version: 3.9.0
    metadataVersion: 3.9
    replicas: 3
    config:
      inter.broker.protocol.version: 3.9
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "8Gi"
        cpu: "4"
    jmxOptions:
      authentication: {}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-cluster-config
          key: metrics-config
    entityOperator:
      topicOperator: {}
      userOperator: {}