apiVersion: apps/v1
kind: Deployment
metadata:
  name: authService
  labels:
    app: authService
app:
  replicas: 1
  selector:
    matchLabels:
      app: authService
  template:
    metadata:
      labels:
        app: authService
    spec:
      containers:
        - name: AuthService
          image: authServiceImage
          ports:
            - containerPort: 8080
            - containerPort: 8091
          env:
            - name: AS_PORT
              value: "8080"
            - name: AS_METRICS_PORT
              value: "8091"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-postgresql-pguser-{{ .Values.postgres.username }}
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: auth-postgresql-pguser-{{ .Values.postgres.username }}
                  key: port
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: auth-postgresql-pguser-{{ .Values.postgres.username }}
                  key: dbname
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-postgresql-pguser-{{ .Values.postgres.username }}
                  key: user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-postgresql-pguser-{{ .Values.postgres.username }}
                  key: password