apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresInstance
  namespace: microservices
spec:
  serviceName: "postgres-key-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgresInstance
  template:
    metadata:
      labels:
        app: postgresInstance
    spec:
      containers:
        - name: postgresInstance
          image: postgres:17.4-bookworm
          env:
            - name: POSTGRES_DB
              value: KeyDb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-key-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-key-secret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: "local-path"