apiVersion: v1
kind: Service
metadata:
  name: postgres-key-service
  namespace: microservices
spec:
  selector:
    app: postgresInstance
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432