apiVersion: 1
kind: Secret
metadata:
  name: postgres-key-secret
  namespace: microservices
type: Opaque
data:
  username: S2V5VXNlcg==
  password: YW1TSlZLWj8yKD8naitZbTdGSi5LVEovUHs8TSE+VENhJFdGXXJo