apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: key-service-user
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512