apiVersion: batch/v1
kind: CronJob
metadata:
  name: key-cronjob
  namespace: microservices
spec:
  schedule: "0 2 * * 0"
  startingDeadlineSeconds: 86400
  concurrencyPolicy: Forbid
  timeZone: "Etc/Utc"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          containers:
            - name: key-generator
              image: keyImage
              env:
                - name: KS_PORT
                  value: "8081"
                - name: SPRING_DATASOURCE_URL
                  value: "jdbc:postgresql://postgres-key-service:5432/KeyDb"
                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: postgres-key-secret
                      key: username
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-key-secret
                      key: password
                - name: KAFKA_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: KeyUserSecret
                      key: username
                - name: KAFKA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: KeyUserSecret
                      key: password
                - name: KAFKA_PORT
                  value: "9093"
          restartPolicy: OnFailure