apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: key-service-user
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: auth-service-keys
          patternType: literal
        operations:
          - Write
      - resource:
          type: topic
          name: validation-keys
          patternType: literal
        operations:
          - Write
      - resource:
          type: topic
          name: key-change
          patternType: literal
        operations:
          - Write