apiVersion: v1
kind: Service
metadata:
  name: authenticationService
  labels:
    app: authentication
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: authentication