apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victoria-metrics
spec:
  selector:
    matchLabels:
      app: victoria-metrics
  serviceName: "victoria-metrics-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      containers:
        - name: victoria-metrics
          image: victoriametrics/victoria-metrics:stable
          args:
            - "-storageDataPath=/storage"
          ports:
            - containerPort: 8428
          volumeMounts:
          - name: storage
            mountPath: /storage
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
